// Generated by CoffeeScript 1.12.7
var EmojiChar, punycode;

punycode = require('punycode');

EmojiChar = (function() {
  function EmojiChar(blob) {
    var k, v;
    for (k in blob) {
      v = blob[k];
      this[k] = v;
    }
    if (this.variations == null) {
      this.variations = [];
    }
  }

  EmojiChar.prototype.is_doublebyte = function() {
    return this.unified.indexOf('-') !== -1;
  };

  EmojiChar.prototype.has_variants = function() {
    return this.variations.length > 0;
  };

  EmojiChar.prototype.variant = function() {
    if (!(this.variations.length > 0)) {
      return null;
    }
    return this.variations[0];
  };

  EmojiChar.prototype.render = function(arg) {
    var target, variant_encoding;
    variant_encoding = (arg != null ? arg : {
      variant_encoding: true
    }).variant_encoding;
    target = (function() {
      switch (false) {
        case !(this.has_variants() && variant_encoding):
          return this.variant();
        default:
          return this.unified;
      }
    }).call(this);
    return EmojiChar._unified_to_char(target);
  };

  EmojiChar.prototype.chars = function() {
    var i, id, len, ref, results;
    ref = [this.unified].concat(this.variations);
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      id = ref[i];
      results.push(EmojiChar._unified_to_char(id));
    }
    return results;
  };

  EmojiChar.prototype.toString = function() {
    return this.render();
  };

  EmojiChar._unified_to_char = function(uid) {
    var cp, cps;
    cps = (function() {
      var i, len, ref, results;
      ref = uid.split('-');
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        cp = ref[i];
        results.push(parseInt(cp, 16));
      }
      return results;
    })();
    return punycode.ucs2.encode(cps);
  };

  return EmojiChar;

})();

module.exports = EmojiChar;
